/-
Copyright (c) 2026 Jesse Michael Paul. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jesse Michael Paul
-/
import Concentricity.ASectionActionDiagram
import Concentricity.ASectionCResidue
import Mathlib.CategoryTheory.ObjectProperty.FullSubcategory

/-!
# The framewise C-residue inverse image

At a projective frame `X`, `AsectionActionFiber A X` is the already-certified
groupoid of complete value states generated by the distinguished A-section
action. This file takes the full inverse image of the already-certified
semantic locus `CResidueZeroLocus A` inside that groupoid.

The definition is deliberately displayed as a `Set.preimage`. Its source is
the complete action-state object already carried by `AsectionActionFiber`;
its target is the coercion-image of `CResidueZeroLocus A` in the compactified
coordinate sphere. The semantic locus is therefore named rather than
unfolded, and no residue enumeration, seed, transport, output, or arrow is
installed.

The positioned-coordinate reading is a certified leg of the complete
action-state naturality square. Cross-frame preservation must consume that
whole square; the leg is never treated as an independent action.
-/

noncomputable section

open CategoryTheory

namespace ASection

/-- The named framewise inverse-image property of the semantic C-residue
locus inside the certified whole-action groupoid `F_A(X)`. -/
def IsCResidueState (A : ASection) (X : GreatCircle.Base) :
    ObjectProperty (AsectionActionFiber A X) :=
  fun x =>
    x ∈
      (fun y : AsectionActionFiber A X =>
          y.positioned.back.coordinate) ⁻¹'
        ((fun z : ℂ => (z : OnePoint ℂ)) '' A.CResidueZeroLocus)

/-- The full framewise inverse image of the semantic C-residue locus inside
the certified whole-action groupoid `F_A(X)`. -/
abbrev InverseImageCResidueStateWorldGroupoid
    (A : ASection) (X : GreatCircle.Base) :=
  (IsCResidueState A X).FullSubcategory

instance (A : ASection) (X : GreatCircle.Base) :
    Groupoid (InverseImageCResidueStateWorldGroupoid A X) :=
  inferInstanceAs
    (Groupoid
      (InducedCategory (AsectionActionFiber A X)
        ObjectProperty.FullSubcategory.obj))

end ASection
