/-
Copyright (c) 2026 Jesse Michael Paul. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jesse Michael Paul
-/
import Concentricity.ASectionActionDiagram
import Concentricity.NormalizedBase
import Mathlib.CategoryTheory.Grothendieck

/-!
# The genuine action-generated total

The canonical top-level Grothendieck total of the certified action diagram,
together with its insertion and transport, and the Gate-6 recognition of the
generated residue outputs.

This file contains **only** live, certified material.  The obsolete
point-projection and per-zero north-leg preflights have been removed.
-/

noncomputable section

open CategoryTheory

namespace ASection

/-! ## The genuine action-generated total -/

/-- The accepted action diagram viewed in `Cat`, exactly as required by
the Grothendieck construction. -/
abbrev AsectionActionCatDiagram (A : ASection) :
    GreatCircle.Base ⥤ Cat :=
  AsectionActionDiagram A ⋙ Grpd.forgetToCat

/-- The genuine total category of the complete positioned A-action. -/
abbrev TotalActionStateWorld (A : ASection) :=
  CategoryTheory.Grothendieck (AsectionActionCatDiagram A)

/-- Insert one action-generated fibre state into the genuine total. -/
def totalMk (A : ASection) (X : GreatCircle.Base)
    (x : AsectionActionFiber A X) : TotalActionStateWorld A :=
  ⟨X, x⟩

@[simp] theorem totalMk_base (A : ASection) (X : GreatCircle.Base)
    (x : AsectionActionFiber A X) :
    (totalMk A X x).base = X := rfl

@[simp] theorem totalMk_fiber (A : ASection) (X : GreatCircle.Base)
    (x : AsectionActionFiber A X) :
    (totalMk A X x).fiber = x := rfl

/-- The canonical cocartesian morphism carrying a total object along a
projective base arrow.  Its target is produced by the already-green action
diagram; no connector or output state is supplied separately. -/
def totalTransport (A : ASection) (X : TotalActionStateWorld A)
    {Y : GreatCircle.Base} (f : X.base ⟶ Y) :
    X ⟶ CategoryTheory.Grothendieck.transport X f :=
  CategoryTheory.Grothendieck.toTransport X f

@[simp] theorem totalTransport_base (A : ASection)
    (X : TotalActionStateWorld A)
    {Y : GreatCircle.Base} (f : X.base ⟶ Y) :
    (totalTransport A X f).base = f := rfl

@[simp] theorem totalTransport_fiber (A : ASection)
    (X : TotalActionStateWorld A)
    {Y : GreatCircle.Base} (f : X.base ⟶ Y) :
    (totalTransport A X f).fiber = 𝟙 _ := rfl

/-! ## Gate 6: recognize the generated residue outputs

The accepted fibre over `X` applies the projective frame of `X` to its
input.  Hence the canonical representative of an already-generated residue
state is its inverse-frame preimage.  Applying the fibre action then returns
the actual residue state, whose value is evaluated by the same A-section
action.  Nothing zero-specific is added to the carrier.
-/

/-- The frame-correct fibre representative whose positioned state is the
actual `n`-th residue state in the slice world `I`. -/
noncomputable def residueActionState (A : ASection)
    (X : GreatCircle.Base) (n : ℕ) (I : SphereWorld) :
    AsectionActionFiber A X :=
  AsectionActionState.ofInput A X
    ((coordinateTransport A (projectiveObjectFrame A X)⁻¹).obj
      ((A.residueState n I : AsectionState A) :
        AsectionStateWorld A))

/-- The inverse-frame representative is positioned back at the actual
action-generated residue state. -/
@[simp] theorem residueActionState_positioned (A : ASection)
    (X : GreatCircle.Base) (n : ℕ) (I : SphereWorld) :
    (residueActionState A X n I).positioned =
      ((A.residueState n I : AsectionState A) :
        AsectionStateWorld A) := by
  change
    (coordinateTransport A (projectiveObjectFrame A X)).obj
        ((coordinateTransport A (projectiveObjectFrame A X)⁻¹).obj
          ((A.residueState n I : AsectionState A) :
            AsectionStateWorld A)) =
      ((A.residueState n I : AsectionState A) :
        AsectionStateWorld A)
  change
    ((coordinateTransport A (projectiveObjectFrame A X)⁻¹ ⋙
        coordinateTransport A (projectiveObjectFrame A X)).obj
      ((A.residueState n I : AsectionState A) :
        AsectionStateWorld A)) =
      ((A.residueState n I : AsectionState A) :
        AsectionStateWorld A)
  rw [coordinateTransport_mul]
  simp [coordinateTransport_one]

/-- The canonical total representative of the `n`-th residue sphere in
the slice world `I`.  As `I` ranges over `SphereWorld`, this is the full
`G₂`-swept residue-sphere family already generated by the action. -/
noncomputable def residueTotal (A : ASection) (n : ℕ)
    (I : SphereWorld) : TotalActionStateWorld A :=
  totalMk A (normalizedFootpoint (A.sphereZero n).re)
    (residueActionState A
      (normalizedFootpoint (A.sphereZero n).re) n I)

@[simp] theorem residueTotal_base (A : ASection) (n : ℕ)
    (I : SphereWorld) :
    (residueTotal A n I).base =
      normalizedFootpoint (A.sphereZero n).re := rfl

/-- The genuine total representative retains the actual residue state as
its positioned face. -/
@[simp] theorem residueTotal_positioned (A : ASection) (n : ℕ)
    (I : SphereWorld) :
    (residueTotal A n I).fiber.positioned =
      ((A.residueState n I : AsectionState A) :
        AsectionStateWorld A) :=
  residueActionState_positioned A _ n I

/-- Evaluating the A-section at an enumerated residue point gives the
compactified octonionic zero.  This is a consequence of the existing C3
stem-zero theorem and the slice realization; it is not carrier data. -/
theorem normalizedSectionPoint_eq_zero (A : ASection) (n : ℕ)
    (I : SphereWorld) :
    A.normalizedSectionPoint n I =
      ((0 : Octonion) : OnePoint Octonion) := by
  have him : 0 < (A.sphereZero n).im :=
    A.c3_sphere_nonreal n
  have hzp : A.sphereZero n ≠ (A.pole : ℂ) := by
    intro h
    rw [h] at him
    simp [Complex.ofReal_im] at him
  have hcoord :
      Octonion.sliceCoord
          (Octonion.sliceEmbed I.val (A.sphereZero n)) =
        A.sphereZero n := by
    rw [Octonion.sliceCoord_sliceEmbed I.prop]
    exact Complex.ext rfl (abs_of_pos him)
  have han :
      AnalyticAt ℂ A.F
        (Octonion.sliceCoord
          (Octonion.sliceEmbed I.val (A.sphereZero n))) := by
    rw [hcoord]
    exact A.c1_analyticAt _ hzp
  rw [normalizedSectionPoint, normalizedZeroPoint, normalizedZeroLift,
    A.realize_coe, if_pos han, hcoord,
    Octonion.dir_sliceEmbed_of_pos I.prop him,
    A.stem_zero_of_sphereZero]
  rw [OnePoint.coe_eq_coe]
  rw [show ((0 : ℂ)) = ((0 : ℝ) : ℂ) by norm_num,
    Octonion.sliceEmbed_ofReal]
  rw [Octonion.ofReal]
  norm_num
  rfl

/-- The value carried by the genuine total representative is zero.  The
value is read from the generated output field after identifying its
positioned face with the actual residue state. -/
@[simp] theorem residueTotal_value_back (A : ASection) (n : ℕ)
    (I : SphereWorld) :
    (residueTotal A n I).fiber.value.back =
      ((0 : Octonion) : OnePoint Octonion) := by
  calc
    (residueTotal A n I).fiber.value.back =
        ((AsectionStateOutput A).obj
          (residueTotal A n I).fiber.positioned).back := by
            rw [(residueTotal A n I).fiber.value_realized]
    _ = ((AsectionStateOutput A).obj
          (((A.residueState n I : AsectionState A) :
            AsectionStateWorld A))).back := by
          rw [residueTotal_positioned]
    _ = A.normalizedSectionPoint n I := rfl
    _ = ((0 : Octonion) : OnePoint Octonion) :=
      normalizedSectionPoint_eq_zero A n I

/-- The positioned representative keeps the chosen sphere direction.
Thus the universally quantified `I` in `residueTotal` is the full
`G₂`-swept family, not one selected slice. -/
@[simp] theorem residueTotal_positioned_world (A : ASection) (n : ℕ)
    (I : SphereWorld) :
    (residueTotal A n I).fiber.positioned.back.world = I := by
  rw [residueTotal_positioned]
  rfl

/- The next gate, not this one, consumes the native northward zigzags and
applies the component/colimit machinery to these recognized inhabitants. -/

end ASection
