/-
Copyright (c) 2026 Jesse Michael Paul. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jesse Michael Paul
-/
import Concentricity.ASectionFunctor
import Mathlib.CategoryTheory.Groupoid
import Mathlib.CategoryTheory.Groupoid.Grpd.Basic
import Mathlib.CategoryTheory.InducedCategory

/-!
# The groupoid-valued A-section action diagram

The distinguished Euler--Weierstrass--GPV element is simultaneously a
Möbius group element and the function whose values define the A-section.
Consequently the fibre over a projective object is not a fixed carrier later
decorated by that element.  It is the constrained graph of the complete
action positioned at that object.

An object of `AsectionActionStateWorld A m` retains:

* a normalized octonionic input state;
* the state obtained by applying the Möbius function `m`;
* the value inherited by evaluating the one A-section action there.

The latter two entries are constrained by equalities, so neither can be
chosen independently.  A two-legged `ActionTransportSquare` acts on these
graphs: its right leg transports the input and its left leg transports the
positioned state.  The square's existing `commutes` proof is exactly what
makes the target graph well-defined.

Specializing to `orbitStabilizerActionSquare A f` gives
`AsectionActionDiagram A : GreatCircle.Base ⥤ Grpd`.  Both its object and
arrow assignments are therefore generated by the same distinguished action.
No residue index, common north value, component, or centre occurs here.
-/

noncomputable section

open CategoryTheory

namespace ASection

/-- One value state of the complete A-action positioned by `m`.

`positioned` and `value` are not independent fields: they are forced to be
the result of the Möbius action and the subsequent canonical A-section
evaluation. -/
@[ext]
structure AsectionActionState (A : ASection) (m : Moebius) where
  input : AsectionStateWorld A
  positioned : AsectionStateWorld A
  positioned_by_action :
    positioned = (coordinateTransport A m).obj input
  value : H1
  value_realized :
    value = (AsectionStateOutput A).obj positioned

/-- The groupoid of value states inherited from the A-action positioned by
`m`.  Morphisms are inherited from the normalized input groupoid; the
positioned and value arrows are then generated functorially. -/
abbrev AsectionActionStateWorld (A : ASection) (m : Moebius) :=
  InducedCategory (AsectionStateWorld A)
    (fun x : AsectionActionState A m => x.input)

instance (A : ASection) (m : Moebius) :
    Groupoid (AsectionActionStateWorld A m) :=
  inferInstance

/-- Package the generated-state groupoid as an object of `Grpd`. -/
abbrev AsectionActionStateFiber (A : ASection) (m : Moebius) : Grpd :=
  Grpd.of (AsectionActionStateWorld A m)

/-- Every normalized input produces its positioned state and its A-value.
This is evaluation of the existing function, not installation of output
data. -/
def AsectionActionState.ofInputAt (A : ASection) (m : Moebius)
    (x : AsectionStateWorld A) : AsectionActionState A m where
  input := x
  positioned := (coordinateTransport A m).obj x
  positioned_by_action := rfl
  value :=
    (AsectionStateOutput A).obj ((coordinateTransport A m).obj x)
  value_realized := rfl

/-- The normalized input face of a positioned generated-state fibre. -/
def AsectionActionStateInput (A : ASection) (m : Moebius) :
    AsectionActionStateWorld A m ⥤ AsectionStateWorld A :=
  inducedFunctor
    (fun x : AsectionActionState A m => x.input)

/-- The positioned state face.  Its arrow map is forced by the same Möbius
functor that generated the object field. -/
def AsectionActionStatePositioned (A : ASection) (m : Moebius) :
    AsectionActionStateWorld A m ⥤ AsectionStateWorld A where
  obj x := x.positioned
  map {x y} f :=
    eqToHom x.positioned_by_action ≫
      (coordinateTransport A m).map f.hom ≫
        eqToHom y.positioned_by_action.symm
  map_id x := by simp
  map_comp f g := by simp [Category.assoc]

/-- The octonionic value face inherited by evaluating the one A-action
on the positioned state.  Its object value is propositionally the carried
`value` field by `value_realized`. -/
def AsectionActionStateValue (A : ASection) (m : Moebius) :
    AsectionActionStateWorld A m ⥤ H1 :=
  AsectionActionStatePositioned A m ⋙ AsectionStateOutput A

@[simp] theorem AsectionActionState_ofInputAt_input
    (A : ASection) (m : Moebius) (x : AsectionStateWorld A) :
    (AsectionActionState.ofInputAt A m x).input = x := rfl

@[simp] theorem AsectionActionState_ofInputAt_positioned
    (A : ASection) (m : Moebius) (x : AsectionStateWorld A) :
    (AsectionActionState.ofInputAt A m x).positioned =
      (coordinateTransport A m).obj x := rfl

@[simp] theorem AsectionActionState_ofInputAt_value
    (A : ASection) (m : Moebius) (x : AsectionStateWorld A) :
    (AsectionActionState.ofInputAt A m x).value =
      (AsectionStateOutput A).obj ((coordinateTransport A m).obj x) := rfl

/-- A two-legged action square transports the complete A-section state
graph.  The right leg acts on inputs, the left leg acts on positioned
states, and the value is inherited by evaluating the same A-action
at the transported positioned state. -/
def ActionTransportSquare.actionStateTransport
    {source target : Moebius}
    (square : ActionTransportSquare source target) (A : ASection) :
    AsectionActionStateWorld A source ⥤
      AsectionActionStateWorld A target where
  obj x :=
    { input := (coordinateTransport A square.right).obj x.input
      positioned := (coordinateTransport A square.left).obj x.positioned
      positioned_by_action := by
        calc
          (coordinateTransport A square.left).obj x.positioned =
              (coordinateTransport A square.left).obj
                ((coordinateTransport A source).obj x.input) := by
                  rw [x.positioned_by_action]
          _ = (coordinateTransport A target).obj
                ((coordinateTransport A square.right).obj x.input) := by
                  exact congrArg (fun F => F.obj x.input)
                    (square.coordinateTransport_commutes A)
      value :=
        (AsectionStateOutput A).obj
          ((coordinateTransport A square.left).obj x.positioned)
      value_realized := rfl }
  map f :=
    InducedCategory.homMk
      ((coordinateTransport A square.right).map f.hom)
  map_id x := by
    apply InducedCategory.hom_ext
    rfl
  map_comp f g := by
    apply InducedCategory.hom_ext
    rfl

@[simp] theorem ActionTransportSquare.actionStateTransport_obj_input
    {source target : Moebius}
    (square : ActionTransportSquare source target) (A : ASection)
    (x : AsectionActionStateWorld A source) :
    ((square.actionStateTransport A).obj x).input =
      (coordinateTransport A square.right).obj x.input := rfl

@[simp] theorem ActionTransportSquare.actionStateTransport_obj_positioned
    {source target : Moebius}
    (square : ActionTransportSquare source target) (A : ASection)
    (x : AsectionActionStateWorld A source) :
    ((square.actionStateTransport A).obj x).positioned =
      (coordinateTransport A square.left).obj x.positioned := rfl

@[simp] theorem ActionTransportSquare.actionStateTransport_obj_value
    {source target : Moebius}
    (square : ActionTransportSquare source target) (A : ASection)
    (x : AsectionActionStateWorld A source) :
    ((square.actionStateTransport A).obj x).value =
      (AsectionStateOutput A).obj
        ((coordinateTransport A square.left).obj x.positioned) := rfl

/-- Identity of the graph transport is inherited from the identity action
square. -/
theorem ActionTransportSquare.actionStateTransport_id
    (A : ASection) (m : Moebius) :
    (ActionTransportSquare.id m).actionStateTransport A =
      𝟭 (AsectionActionStateWorld A m) := by
  refine CategoryTheory.Functor.ext (fun x => ?_) (fun x y f => ?_)
  · rcases x with ⟨input, positioned, hpositioned, value, hvalue⟩
    subst positioned
    subst value
    rfl
  · rcases x with ⟨inputX, positionedX, hpositionedX, valueX, hvalueX⟩
    subst positionedX
    subst valueX
    rcases y with ⟨inputY, positionedY, hpositionedY, valueY, hvalueY⟩
    subst positionedY
    subst valueY
    apply InducedCategory.hom_ext
    rfl

/-- Composition of graph transports is inherited from composition of the
underlying two-legged action squares. -/
theorem ActionTransportSquare.actionStateTransport_comp
    (A : ASection) {a b c : Moebius}
    (f : ActionTransportSquare a b) (g : ActionTransportSquare b c) :
    (f.comp g).actionStateTransport A =
      f.actionStateTransport A ⋙ g.actionStateTransport A := by
  refine CategoryTheory.Functor.ext (fun x => ?_) (fun x y h => ?_)
  · apply AsectionActionState.ext <;> rfl
  · apply InducedCategory.hom_ext
    rfl

/-- The complete value-state fibre generated by A's positioned action at
the projective object `X`. -/
abbrev AsectionActionFiber (A : ASection) (X : GreatCircle.Base) : Grpd :=
  AsectionActionStateFiber A (projectiveObjectFrame A X)

/-- Every normalized state occurs in every positioned fibre.  Its
positioned state and octonionic value are generated by the distinguished
action at that projective position. -/
def AsectionActionState.ofInput (A : ASection) (X : GreatCircle.Base)
    (x : AsectionStateWorld A) : AsectionActionFiber A X :=
  AsectionActionState.ofInputAt A (projectiveObjectFrame A X) x

/-- Every sphere direction and compactified slice coordinate occurs in
every projectively positioned fibre. -/
def AsectionActionState.ofCoordinate (A : ASection) (X : GreatCircle.Base)
    (I : SphereWorld) (z : OnePoint ℂ) : AsectionActionFiber A X :=
  AsectionActionState.ofInput A X
    (({ world := I, coordinate := z } : AsectionState A) :
      AsectionStateWorld A)

/-- The input eye of the positioned A-section fibre at `X`. -/
def AsectionActionInput (A : ASection) (X : GreatCircle.Base) :
    AsectionActionFiber A X ⥤ AsectionStateWorld A :=
  AsectionActionStateInput A (projectiveObjectFrame A X)

/-- The projectively positioned state eye of the fibre at `X`. -/
def AsectionActionPositioned (A : ASection) (X : GreatCircle.Base) :
    AsectionActionFiber A X ⥤ AsectionStateWorld A :=
  AsectionActionStatePositioned A (projectiveObjectFrame A X)

/-- The one output eye obtained by evaluating the complete A-action on the
positioned state. -/
def AsectionActionOutput (A : ASection) (X : GreatCircle.Base) :
    AsectionActionFiber A X ⥤ H1 :=
  AsectionActionStateValue A (projectiveObjectFrame A X)

/-- The positioned output is the canonical state output by construction;
there is no second output functor in the action diagram. -/
theorem AsectionActionOutput_eq
    (A : ASection) (X : GreatCircle.Base) :
    AsectionActionOutput A X =
      AsectionActionPositioned A X ⋙ AsectionStateOutput A := rfl

@[simp] theorem AsectionActionState_ofInput_input
    (A : ASection) (X : GreatCircle.Base)
    (x : AsectionStateWorld A) :
    (AsectionActionState.ofInput A X x).input = x := rfl

@[simp] theorem AsectionActionState_ofInput_positioned
    (A : ASection) (X : GreatCircle.Base)
    (x : AsectionStateWorld A) :
    (AsectionActionState.ofInput A X x).positioned =
      (coordinateTransport A (projectiveObjectFrame A X)).obj x := rfl

@[simp] theorem AsectionActionState_ofInput_value
    (A : ASection) (X : GreatCircle.Base)
    (x : AsectionStateWorld A) :
    (AsectionActionState.ofInput A X x).value =
      (AsectionStateOutput A).obj
        ((coordinateTransport A
          (projectiveObjectFrame A X)).obj x) := rfl

/-- Transport between the distinct positioned value-state fibres supplied
by the native orbit--stabilizer action square. -/
def AsectionActionTransport (A : ASection)
    {X Y : GreatCircle.Base} (f : X ⟶ Y) :
    AsectionActionFiber A X ⟶ AsectionActionFiber A Y :=
  (orbitStabilizerActionSquare A f).actionStateTransport A

@[simp] theorem AsectionActionTransport_obj_input (A : ASection)
    {X Y : GreatCircle.Base} (f : X ⟶ Y)
    (x : AsectionActionFiber A X) :
    ((AsectionActionTransport A f).obj x).input =
      (coordinateTransport A
        (orbitStabilizerActionSquare A f).right).obj x.input := rfl

@[simp] theorem AsectionActionTransport_obj_positioned (A : ASection)
    {X Y : GreatCircle.Base} (f : X ⟶ Y)
    (x : AsectionActionFiber A X) :
    ((AsectionActionTransport A f).obj x).positioned =
      (coordinateTransport A
        (orbitStabilizerActionSquare A f).left).obj x.positioned := rfl

@[simp] theorem AsectionActionTransport_obj_value (A : ASection)
    {X Y : GreatCircle.Base} (f : X ⟶ Y)
    (x : AsectionActionFiber A X) :
    ((AsectionActionTransport A f).obj x).value =
      (AsectionStateOutput A).obj
        ((coordinateTransport A
          (orbitStabilizerActionSquare A f).left).obj x.positioned) := rfl

theorem AsectionActionTransport_id (A : ASection)
    (X : GreatCircle.Base) :
    AsectionActionTransport A (𝟙 X) =
      𝟙 (AsectionActionFiber A X) := by
  rw [AsectionActionTransport, orbitStabilizerActionSquare_id]
  exact ActionTransportSquare.actionStateTransport_id A _

theorem AsectionActionTransport_comp (A : ASection)
    {X Y Z : GreatCircle.Base} (f : X ⟶ Y) (g : Y ⟶ Z) :
    AsectionActionTransport A (f ≫ g) =
      AsectionActionTransport A f ⋙ AsectionActionTransport A g := by
  rw [AsectionActionTransport, orbitStabilizerActionSquare_comp]
  exact ActionTransportSquare.actionStateTransport_comp A _ _

/-- The A-section action diagram generated by the one distinguished
function/Möbius element in every projective position. -/
def AsectionActionDiagram (A : ASection) : GreatCircle.Base ⥤ Grpd where
  obj X := AsectionActionFiber A X
  map f := AsectionActionTransport A f
  map_id X := AsectionActionTransport_id A X
  map_comp f g := AsectionActionTransport_comp A f g

end ASection
