/-
Copyright (c) 2026 Jesse Michael Paul. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jesse Michael Paul
-/
import Concentricity.ASectionFunctor
import Mathlib.CategoryTheory.Groupoid
import Mathlib.CategoryTheory.Groupoid.Grpd.Basic
import Mathlib.CategoryTheory.InducedCategory

/-!
# The groupoid-valued A-section action diagram

The distinguished Euler--Weierstrass--GPV element is simultaneously a
Möbius group element and the function whose values define the A-section.
Consequently the fibre over a projective object is not a fixed carrier later
decorated by that element.  It is the constrained graph of the complete
action positioned at that object.

An object of `AsectionActionStateWorld A m` retains:

* a normalized octonionic input state;
* the state obtained by applying the Möbius function `m`;
* the value inherited by evaluating the one A-section action there.

The latter two entries are constrained by equalities, so neither can be
chosen independently.  A two-legged `ActionTransportSquare` acts on these
graphs: its right leg transports the input and its left leg transports the
positioned state.  The square's existing `commutes` proof is exactly what
makes the target graph well-defined.

Specializing to `orbitStabilizerActionSquare A f` gives
`AsectionActionDiagram A : GreatCircle.Base ⥤ Grpd`.  Both its object and
arrow assignments are therefore generated by the same distinguished action.
No residue index, common north value, component, or centre occurs here.
-/

noncomputable section

open CategoryTheory

namespace ASection

/-- One value state of the complete A-action positioned by `m`.

`positioned` and `value` are not independent fields: they are forced to be
the result of the Möbius action and the subsequent canonical A-section
evaluation. -/
@[ext]
structure AsectionActionState (A : ASection) (m : Moebius) where
  input : AsectionStateWorld A
  positioned : AsectionStateWorld A
  positioned_by_action :
    positioned = (coordinateTransport A m).obj input
  value : H1
  value_realized :
    value = (AsectionStateOutput A).obj positioned

/-- The groupoid of value states inherited from the A-action positioned by
`m`.  Morphisms are inherited from the normalized input groupoid; the
positioned and value arrows are then generated functorially. -/
abbrev AsectionActionStateWorld (A : ASection) (m : Moebius) :=
  InducedCategory (AsectionStateWorld A)
    (fun x : AsectionActionState A m => x.input)

instance (A : ASection) (m : Moebius) :
    Groupoid (AsectionActionStateWorld A m) :=
  inferInstance

/-- Package the generated-state groupoid as an object of `Grpd`. -/
abbrev AsectionActionStateFiber (A : ASection) (m : Moebius) : Grpd :=
  Grpd.of (AsectionActionStateWorld A m)

/-- Every normalized input produces its positioned state and its A-value.
This is evaluation of the existing function, not installation of output
data. -/
def AsectionActionState.ofInputAt (A : ASection) (m : Moebius)
    (x : AsectionStateWorld A) : AsectionActionState A m where
  input := x
  positioned := (coordinateTransport A m).obj x
  positioned_by_action := rfl
  value :=
    (AsectionStateOutput A).obj ((coordinateTransport A m).obj x)
  value_realized := rfl

/-- The normalized input face of a positioned generated-state fibre. -/
def AsectionActionStateInput (A : ASection) (m : Moebius) :
    AsectionActionStateWorld A m ⥤ AsectionStateWorld A :=
  inducedFunctor
    (fun x : AsectionActionState A m => x.input)

/-- The positioned state face.  Its arrow map is forced by the same Möbius
functor that generated the object field. -/
def AsectionActionStatePositioned (A : ASection) (m : Moebius) :
    AsectionActionStateWorld A m ⥤ AsectionStateWorld A where
  obj x := x.positioned
  map {x y} f :=
    eqToHom x.positioned_by_action ≫
      (coordinateTransport A m).map f.hom ≫
        eqToHom y.positioned_by_action.symm
  map_id x := by simp
  map_comp f g := by simp [Category.assoc]

/-- The octonionic value face inherited by evaluating the one A-action
on the positioned state.  Its object value is propositionally the carried
`value` field by `value_realized`. -/
def AsectionActionStateValue (A : ASection) (m : Moebius) :
    AsectionActionStateWorld A m ⥤ H1 :=
  AsectionActionStatePositioned A m ⋙ AsectionStateOutput A

@[simp] theorem AsectionActionState_ofInputAt_input
    (A : ASection) (m : Moebius) (x : AsectionStateWorld A) :
    (AsectionActionState.ofInputAt A m x).input = x := rfl

@[simp] theorem AsectionActionState_ofInputAt_positioned
    (A : ASection) (m : Moebius) (x : AsectionStateWorld A) :
    (AsectionActionState.ofInputAt A m x).positioned =
      (coordinateTransport A m).obj x := rfl

@[simp] theorem AsectionActionState_ofInputAt_value
    (A : ASection) (m : Moebius) (x : AsectionStateWorld A) :
    (AsectionActionState.ofInputAt A m x).value =
      (AsectionStateOutput A).obj ((coordinateTransport A m).obj x) := rfl

/-- A two-legged action square transports the complete A-section state
graph.  The right leg acts on inputs, the left leg acts on positioned
states, and the value is inherited by evaluating the same A-action
at the transported positioned state. -/
def ActionTransportSquare.actionStateTransport
    {source target : Moebius}
    (square : ActionTransportSquare source target) (A : ASection) :
    AsectionActionStateWorld A source ⥤
      AsectionActionStateWorld A target where
  obj x :=
    { input := (coordinateTransport A square.right).obj x.input
      positioned := (coordinateTransport A square.left).obj x.positioned
      positioned_by_action := by
        calc
          (coordinateTransport A square.left).obj x.positioned =
              (coordinateTransport A square.left).obj
                ((coordinateTransport A source).obj x.input) := by
                  rw [x.positioned_by_action]
          _ = (coordinateTransport A target).obj
                ((coordinateTransport A square.right).obj x.input) := by
                  exact congrArg (fun F => F.obj x.input)
                    (square.coordinateTransport_commutes A)
      value :=
        (AsectionStateOutput A).obj
          ((coordinateTransport A square.left).obj x.positioned)
      value_realized := rfl }
  map f :=
    InducedCategory.homMk
      ((coordinateTransport A square.right).map f.hom)
  map_id x := by
    apply InducedCategory.hom_ext
    rfl
  map_comp f g := by
    apply InducedCategory.hom_ext
    rfl

@[simp] theorem ActionTransportSquare.actionStateTransport_obj_input
    {source target : Moebius}
    (square : ActionTransportSquare source target) (A : ASection)
    (x : AsectionActionStateWorld A source) :
    ((square.actionStateTransport A).obj x).input =
      (coordinateTransport A square.right).obj x.input := rfl

@[simp] theorem ActionTransportSquare.actionStateTransport_obj_positioned
    {source target : Moebius}
    (square : ActionTransportSquare source target) (A : ASection)
    (x : AsectionActionStateWorld A source) :
    ((square.actionStateTransport A).obj x).positioned =
      (coordinateTransport A square.left).obj x.positioned := rfl

@[simp] theorem ActionTransportSquare.actionStateTransport_obj_value
    {source target : Moebius}
    (square : ActionTransportSquare source target) (A : ASection)
    (x : AsectionActionStateWorld A source) :
    ((square.actionStateTransport A).obj x).value =
      (AsectionStateOutput A).obj
        ((coordinateTransport A square.left).obj x.positioned) := rfl

/-- Identity of the graph transport is inherited from the identity action
square. -/
theorem ActionTransportSquare.actionStateTransport_id
    (A : ASection) (m : Moebius) :
    (ActionTransportSquare.id m).actionStateTransport A =
      𝟭 (AsectionActionStateWorld A m) := by
  refine CategoryTheory.Functor.ext (fun x => ?_) (fun x y f => ?_)
  · rcases x with ⟨input, positioned, hpositioned, value, hvalue⟩
    subst positioned
    subst value
    rfl
  · rcases x with ⟨inputX, positionedX, hpositionedX, valueX, hvalueX⟩
    subst positionedX
    subst valueX
    rcases y with ⟨inputY, positionedY, hpositionedY, valueY, hvalueY⟩
    subst positionedY
    subst valueY
    apply InducedCategory.hom_ext
    rfl

/-- Composition of graph transports is inherited from composition of the
underlying two-legged action squares. -/
theorem ActionTransportSquare.actionStateTransport_comp
    (A : ASection) {a b c : Moebius}
    (f : ActionTransportSquare a b) (g : ActionTransportSquare b c) :
    (f.comp g).actionStateTransport A =
      f.actionStateTransport A ⋙ g.actionStateTransport A := by
  refine CategoryTheory.Functor.ext (fun x => ?_) (fun x y h => ?_)
  · apply AsectionActionState.ext <;> rfl
  · apply InducedCategory.hom_ext
    rfl

/-- The complete value-state fibre generated by A's positioned action at
the projective object `X`. -/
abbrev AsectionActionFiber (A : ASection) (X : GreatCircle.Base) : Grpd :=
  AsectionActionStateFiber A (projectiveObjectFrame A X)

/-- Every normalized state occurs in every positioned fibre.  Its
positioned state and octonionic value are generated by the distinguished
action at that projective position. -/
def AsectionActionState.ofInput (A : ASection) (X : GreatCircle.Base)
    (x : AsectionStateWorld A) : AsectionActionFiber A X :=
  AsectionActionState.ofInputAt A (projectiveObjectFrame A X) x

/-- Every sphere direction and compactified slice coordinate occurs in
every projectively positioned fibre. -/
def AsectionActionState.ofCoordinate (A : ASection) (X : GreatCircle.Base)
    (I : SphereWorld) (z : OnePoint ℂ) : AsectionActionFiber A X :=
  AsectionActionState.ofInput A X
    (({ world := I, coordinate := z } : AsectionState A) :
      AsectionStateWorld A)

/-- The input eye of the positioned A-section fibre at `X`. -/
def AsectionActionInput (A : ASection) (X : GreatCircle.Base) :
    AsectionActionFiber A X ⥤ AsectionStateWorld A :=
  AsectionActionStateInput A (projectiveObjectFrame A X)

/-- The projectively positioned state eye of the fibre at `X`. -/
def AsectionActionPositioned (A : ASection) (X : GreatCircle.Base) :
    AsectionActionFiber A X ⥤ AsectionStateWorld A :=
  AsectionActionStatePositioned A (projectiveObjectFrame A X)

/-- The one output eye obtained by evaluating the complete A-action on the
positioned state. -/
def AsectionActionOutput (A : ASection) (X : GreatCircle.Base) :
    AsectionActionFiber A X ⥤ H1 :=
  AsectionActionStateValue A (projectiveObjectFrame A X)

/-- The positioned output is the canonical state output by construction;
there is no second output functor in the action diagram. -/
theorem AsectionActionOutput_eq
    (A : ASection) (X : GreatCircle.Base) :
    AsectionActionOutput A X =
      AsectionActionPositioned A X ⋙ AsectionStateOutput A := rfl

/-- The value eye of the positioned action graph is the input eye followed
by the equivariant realization of this same fixed A-section.  This is the
explicit in/out triangle for the accepted action fibre; no ambient Cayley
value functor and no independently chosen output enters the graph. -/
theorem AsectionActionOutput_eq_input_then_equivariant
    (A : ASection) (X : GreatCircle.Base) :
    AsectionActionOutput A X =
      (AsectionActionPositioned A X ⋙ AsectionStateInput A) ⋙
        A.AsectionEquivariant := by
  calc
    AsectionActionOutput A X =
        AsectionActionPositioned A X ⋙ AsectionStateOutput A := rfl
    _ = AsectionActionPositioned A X ⋙
        (AsectionStateInput A ⋙ A.AsectionEquivariant) :=
      congrArg (fun F => AsectionActionPositioned A X ⋙ F)
        (AsectionState_input_then_equivariant A).symm
    _ = (AsectionActionPositioned A X ⋙ AsectionStateInput A) ⋙
        A.AsectionEquivariant := rfl

/-- Objectwise reading of the same fixed-A triangle: the stored value is
exactly `AsectionEquivariant A` evaluated on the positioned input eye. -/
theorem AsectionActionState_value_eq_equivariant_input
    (A : ASection) {X : GreatCircle.Base}
    (x : AsectionActionFiber A X) :
    x.value =
      (A.AsectionEquivariant).obj
        ((AsectionStateInput A).obj x.positioned) := by
  calc
    x.value = (AsectionStateOutput A).obj x.positioned := x.value_realized
    _ = (AsectionStateInput A ⋙ A.AsectionEquivariant).obj x.positioned :=
      congrArg (fun F : AsectionStateWorld A ⥤ H1 => F.obj x.positioned)
        (AsectionState_input_then_equivariant A).symm
    _ = (A.AsectionEquivariant).obj
        ((AsectionStateInput A).obj x.positioned) := rfl

@[simp] theorem AsectionActionState_ofInput_input
    (A : ASection) (X : GreatCircle.Base)
    (x : AsectionStateWorld A) :
    (AsectionActionState.ofInput A X x).input = x := rfl

@[simp] theorem AsectionActionState_ofInput_positioned
    (A : ASection) (X : GreatCircle.Base)
    (x : AsectionStateWorld A) :
    (AsectionActionState.ofInput A X x).positioned =
      (coordinateTransport A (projectiveObjectFrame A X)).obj x := rfl

@[simp] theorem AsectionActionState_ofInput_value
    (A : ASection) (X : GreatCircle.Base)
    (x : AsectionStateWorld A) :
    (AsectionActionState.ofInput A X x).value =
      (AsectionStateOutput A).obj
        ((coordinateTransport A
          (projectiveObjectFrame A X)).obj x) := rfl

/-- Transport between the distinct positioned value-state fibres supplied
by the native orbit--stabilizer action square. -/
def AsectionActionTransport (A : ASection)
    {X Y : GreatCircle.Base} (f : X ⟶ Y) :
    AsectionActionFiber A X ⟶ AsectionActionFiber A Y :=
  (orbitStabilizerActionSquare A f).actionStateTransport A

/-- master `def:gpv-transport`, `def:transport`: the GPV action square on
the actual source and target fibres. The endpoint identifications are
proved from the continued factor, before constructing the state transport. -/
def GpvTransport.stateActionSquare {A : ASection}
    {X Y : GreatCircle.Base} (τ : GpvTransport A X Y) (f : X ⟶ Y) :
    ActionTransportSquare (projectiveObjectFrame A X)
      (projectiveObjectFrame A Y) where
  left := (projectiveGpvActionSquare A f τ).left
  right := (orbitStabilizerActionSquare A f).right
  commutes := by
    rw [← (projectiveGpvActionSquare_legs A f τ).2]
    simpa only [τ.diskExpAction_zero, τ.diskExpAction_one] using
      (projectiveGpvActionSquare A f τ).commutes

/-- The GPV square and the production square are equal as whole squares,
including their input leg, rather than only their positioned matrix. -/
theorem GpvTransport.stateActionSquare_eq {A : ASection}
    {X Y : GreatCircle.Base} (τ : GpvTransport A X Y) (f : X ⟶ Y) :
    τ.stateActionSquare f = orbitStabilizerActionSquare A f := by
  apply ActionTransportSquare.ext
  · exact (projectiveGpvActionSquare_legs A f τ).1
  · rfl

/-- master `def:transport`: apply the GPV square to the complete graph of
the A-section's equivariant realization. -/
def GpvTransport.stateTransport {A : ASection}
    {X Y : GreatCircle.Base} (τ : GpvTransport A X Y) (f : X ⟶ Y) :
    AsectionActionFiber A X ⥤ AsectionActionFiber A Y :=
  (τ.stateActionSquare f).actionStateTransport A

/-- Equality of the complete functors identifies GPV transport with the
transport in `A_A`, including its positioned state, value, and G₂ arrows. -/
theorem GpvTransport.stateTransport_eq {A : ASection}
    {X Y : GreatCircle.Base} (τ : GpvTransport A X Y) (f : X ⟶ Y) :
    τ.stateTransport f = AsectionActionTransport A f := by
  unfold GpvTransport.stateTransport
  rw [τ.stateActionSquare_eq]
  rfl

/-- The choice of GPV run or logarithmic lift does not change the complete
state functor assigned to the given projective arrow. -/
theorem GpvTransport.stateTransport_independent {A : ASection}
    {X Y : GreatCircle.Base} (τ σ : GpvTransport A X Y) (f : X ⟶ Y) :
    τ.stateTransport f = σ.stateTransport f := by
  rw [τ.stateTransport_eq, σ.stateTransport_eq]

/-- master `lem:exp-degenerate`, `def:states`: all directions and winding
branches of the negative-real source fibre give the same actual source
groupoid of `A_A`. This applies the full octonionic fibre theorem. -/
theorem GpvTransport.degenerate_source_state_fibre {A : ASection}
    {X Y : GreatCircle.Base} (τ : GpvTransport A X Y)
    {r : ℝ} (hr : 0 < r) (hv : τ.value 0 = -(r : ℂ))
    (q : Octonion) (hq : Octonion.exp q = Octonion.ofReal (-r)) :
    ∃ I : SphereWorld, ∃ k : ℤ,
      q = Octonion.sliceEmbed I.val
        ⟨Real.log r, ((2 * k + 1 : ℤ) : ℝ) * Real.pi⟩ ∧
      Octonion.re q = Real.log r ∧
      AsectionActionStateFiber A (GreatCircle.diskExpAction
        ⟨Real.log r, ((2 * k + 1 : ℤ) : ℝ) * Real.pi⟩) =
          AsectionActionFiber A X := by
  obtain ⟨I, k, hq', hm, hreal⟩ :=
    (τ.source_degenerate_fibre_action hr hv q).mp hq
  exact ⟨I, k, hq', hreal, congrArg (AsectionActionStateFiber A) hm⟩

/-- master `rmk:gpv-real-fibre`, `def:states`: every logarithm in the
source exponential fibre gives the same state groupoid and real level.
This has no sign restriction on the continued multiplier. -/
theorem GpvTransport.source_fibre_state_and_level {A : ASection}
    {X Y : GreatCircle.Base} (τ : GpvTransport A X Y)
    (w : ℂ) (hw : Complex.exp w = τ.value 0) :
    AsectionActionStateFiber A (GreatCircle.diskExpAction w) =
      AsectionActionFiber A X ∧ w.re = (τ.lift 0).re := by
  have he : Complex.exp w = Complex.exp (τ.lift 0) :=
    hw.trans (τ.lift_exp 0).symm
  have hm : GreatCircle.diskExpAction w =
      GreatCircle.diskExpAction (τ.lift 0) := by
    apply congrArg GreatCircle.diskDiagonalMoebiusHom
    exact Units.ext he
  constructor
  · rw [hm, τ.diskExpAction_zero]
  · have hn := congrArg (fun z : ℂ => ‖z‖) he
    simp only [Complex.norm_exp] at hn
    exact Real.exp_injective hn

/-- The target version of the same GPV fibre statement. -/
theorem GpvTransport.target_fibre_state_and_level {A : ASection}
    {X Y : GreatCircle.Base} (τ : GpvTransport A X Y)
    (w : ℂ) (hw : Complex.exp w = τ.value 1) :
    AsectionActionStateFiber A (GreatCircle.diskExpAction w) =
      AsectionActionFiber A Y ∧ w.re = (τ.lift 1).re := by
  have he : Complex.exp w = Complex.exp (τ.lift 1) :=
    hw.trans (τ.lift_exp 1).symm
  have hm : GreatCircle.diskExpAction w =
      GreatCircle.diskExpAction (τ.lift 1) := by
    apply congrArg GreatCircle.diskDiagonalMoebiusHom
    exact Units.ext he
  constructor
  · rw [hm, τ.diskExpAction_one]
  · have hn := congrArg (fun z : ℂ => ‖z‖) he
    simp only [Complex.norm_exp] at hn
    exact Real.exp_injective hn

/-- master `def:DA`, `def:states`: the C1-regularized multiplier generates
the state groupoid at the pole. -/
theorem regularizedPoleChart_state_fibre (A : ASection) :
    AsectionActionStateFiber A
      (A.regularizedPoleChartAction (A.pole : ℂ)
        A.distinguishedPoleFactor_ne_zero) =
      AsectionActionFiber A (projectivePole A) := by
  rw [A.regularizedPoleChartAction_at_pole]
  change AsectionActionStateFiber A A.distinguishedDiskAction =
    AsectionActionStateFiber A (projectiveObjectFrame A (projectivePole A))
  rw [projectiveObjectFrame_pole]

/-- master `def:DA`, `def:states`: the already-proved Euler and
Weierstrass matrix identities identify the complete generated state
groupoids on the punctured pole chart. -/
theorem euler_weierstrass_state_fibres (A : ASection) :
    ∀ᶠ z in nhdsWithin (A.pole : ℂ) {(A.pole : ℂ)}ᶜ,
      ∃ (hg : A.distinguishedPoleFactor z ≠ 0)
        (hp : z - (A.pole : ℂ) ≠ 0)
        (hw : z ^ A.m * A.Rfac z * Complex.exp (A.gfac z) *
          ∏' n, spherePrimary (A.genus n) (A.sphereZero n) z ≠ 0),
        (A.Ω₀ < z.re →
          AsectionActionStateFiber A (A.regularizedPoleChartAction z hg) =
            AsectionActionStateFiber A
              (GreatCircle.diskDiagonalMoebiusHom
                (Units.mk0 (z - (A.pole : ℂ)) hp) * A.eulerDiskAction z)) ∧
        AsectionActionStateFiber A (A.regularizedPoleChartAction z hg) =
          AsectionActionStateFiber A
            (GreatCircle.diskDiagonalMoebiusHom
              (Units.mk0 (z ^ A.m * A.Rfac z * Complex.exp (A.gfac z) *
                ∏' n, spherePrimary (A.genus n) (A.sphereZero n) z) hw)) := by
  filter_upwards [A.distinguished_euler_weierstrass_one_action]
    with z hz
  obtain ⟨hg, hp, hw, he, hw'⟩ := hz
  exact ⟨hg, hp, hw,
    fun hhalf => congrArg (AsectionActionStateFiber A) (he hhalf),
    congrArg (AsectionActionStateFiber A) hw'⟩

/-- The regularized Euler/GPV boundary acts on the constrained physical
states by exactly the transport used in `AsectionActionDiagram`.  This is
the functor-level face of the boundary-square binding. -/
theorem eulerWeierstrassNorthBoundary_actionStateTransport
    (A : ASection) {X Y : GreatCircle.Base} (f : X ⟶ Y) :
    (A.eulerWeierstrassNorthBoundarySquare f).actionStateTransport A =
      AsectionActionTransport A f := by
  rw [A.eulerWeierstrassNorthBoundarySquare_eq_orbitStabilizer]
  rfl

@[simp] theorem AsectionActionTransport_obj_input (A : ASection)
    {X Y : GreatCircle.Base} (f : X ⟶ Y)
    (x : AsectionActionFiber A X) :
    ((AsectionActionTransport A f).obj x).input =
      (coordinateTransport A
        (orbitStabilizerActionSquare A f).right).obj x.input := rfl

@[simp] theorem AsectionActionTransport_obj_positioned (A : ASection)
    {X Y : GreatCircle.Base} (f : X ⟶ Y)
    (x : AsectionActionFiber A X) :
    ((AsectionActionTransport A f).obj x).positioned =
      (coordinateTransport A
        (orbitStabilizerActionSquare A f).left).obj x.positioned := rfl

/-- master `def:transport`, the normalized-input entry read directly: the
transported input is the source input acted on by the one composition
`A^slice(b)⁻¹ · A^slice(h) · A^slice(a)` the master displays — equal to the
square's right leg by
`orbitStabilizerActionSquare_right_eq_frame_conjugation`. -/
theorem AsectionActionTransport_obj_input_frame_conjugation (A : ASection)
    {X Y : GreatCircle.Base} (f : X ⟶ Y)
    (x : AsectionActionFiber A X) :
    ((AsectionActionTransport A f).obj x).input =
      (coordinateTransport A
        ((projectiveObjectFrame A Y)⁻¹ * projectiveArrowElement A f *
          projectiveObjectFrame A X)).obj x.input := by
  rw [AsectionActionTransport_obj_input,
    orbitStabilizerActionSquare_right_eq_frame_conjugation]

/-- master `def:transport`, the middle entry: the positioned state moves by
the assigned action `A^slice(h)` itself. -/
theorem AsectionActionTransport_obj_positioned_arrowElement (A : ASection)
    {X Y : GreatCircle.Base} (f : X ⟶ Y)
    (x : AsectionActionFiber A X) :
    ((AsectionActionTransport A f).obj x).positioned =
      (coordinateTransport A
        (projectiveArrowElement A f)).obj x.positioned := rfl

@[simp] theorem AsectionActionTransport_obj_value (A : ASection)
    {X Y : GreatCircle.Base} (f : X ⟶ Y)
    (x : AsectionActionFiber A X) :
    ((AsectionActionTransport A f).obj x).value =
      (AsectionStateOutput A).obj
        ((coordinateTransport A
          (orbitStabilizerActionSquare A f).left).obj x.positioned) := rfl

theorem AsectionActionTransport_id (A : ASection)
    (X : GreatCircle.Base) :
    AsectionActionTransport A (𝟙 X) =
      𝟙 (AsectionActionFiber A X) := by
  rw [AsectionActionTransport, orbitStabilizerActionSquare_id]
  exact ActionTransportSquare.actionStateTransport_id A _

theorem AsectionActionTransport_comp (A : ASection)
    {X Y Z : GreatCircle.Base} (f : X ⟶ Y) (g : Y ⟶ Z) :
    AsectionActionTransport A (f ≫ g) =
      AsectionActionTransport A f ⋙ AsectionActionTransport A g := by
  rw [AsectionActionTransport, orbitStabilizerActionSquare_comp]
  exact ActionTransportSquare.actionStateTransport_comp A _ _

/-- The A-section action diagram generated by the one distinguished
function/Möbius element in every projective position. -/
def AsectionActionDiagram (A : ASection) : GreatCircle.Base ⥤ Grpd where
  obj X := AsectionActionFiber A X
  map f := AsectionActionTransport A f
  map_id X := AsectionActionTransport_id A X
  map_comp f g := AsectionActionTransport_comp A f g

end ASection
