/-
Copyright (c) 2026 Jesse Michael Paul. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jesse Michael Paul
-/
import Concentricity.ASectionGenerated
import Concentricity.ASectionFunctor

/-!
# Auxiliary unfolded-presentation certificate

The canonical global A-section action is `AsectionEquivariant`; its
input/output naturality and the two-legged orbit--stabilizer/GPV squares
live in `ASectionFunctor.lean`.

This file retains an independently unfolded `A.Fstar` formula and proves
that it is the same functor.  These declarations are coherence receipts for
one action, not a second action and not the input of
`AsectionActionDiagram`.

Reading a certified square through the unfolded formula preserves
commutativity because the canonical coordinate square already commutes.

No residue output, common north value, or common centre is introduced here.
-/

noncomputable section

open CategoryTheory

namespace ASection

/-- The output generated by the distinguished action from each normalized
state.  This is a functorial composite, not an object-level reader. -/
def AsectionStateGenerated (A : ASection) :
    AsectionStateWorld A ⥤ H1 :=
  AsectionStateInput A ⋙ A.AsectionGenerated

/-- On normalized states, the unfolded formula is the canonical output. -/
theorem AsectionStateGenerated_eq_output (A : ASection) :
    A.AsectionStateGenerated = AsectionStateOutput A := by
  calc
    A.AsectionStateGenerated =
        AsectionStateInput A ⋙ A.AsectionEquivariant := by
      exact congrArg (fun F => AsectionStateInput A ⋙ F)
        A.AsectionGenerated_eq_equivariant
    _ = AsectionStateOutput A :=
      AsectionState_input_then_equivariant A

/-- The natural equality certificate between the unfolded and canonical
output formulae on the normalized state groupoid. -/
def AsectionStateGeneratedIsoOutput (A : ASection) :
    A.AsectionStateGenerated ≅ AsectionStateOutput A :=
  eqToIso A.AsectionStateGenerated_eq_output

/-- The same two-legged action square commutes after reading the output
through the auxiliary unfolded formula. -/
theorem ActionTransportSquare.generated_commutes
    {source target : Moebius}
    (square : ActionTransportSquare source target) (A : ASection) :
    (coordinateTransport A source ⋙ coordinateTransport A square.left) ⋙
        A.AsectionStateGenerated =
      (coordinateTransport A square.right ⋙
          coordinateTransport A target) ⋙
        A.AsectionStateGenerated := by
  rw [square.coordinateTransport_commutes A]

/-- Identity of the completed generated action is inherited from the
identity action square. -/
theorem AsectionStateGenerated_actionSquare_id (A : ASection) (a : Moebius) :
    (coordinateTransport A a ⋙ coordinateTransport A 1) ⋙
        A.AsectionStateGenerated =
      (coordinateTransport A 1 ⋙ coordinateTransport A a) ⋙
        A.AsectionStateGenerated :=
  (ActionTransportSquare.id a).generated_commutes A

/-- Composition of completed generated-action squares is inherited from
composition of the underlying two-legged action squares. -/
theorem AsectionStateGenerated_actionSquare_comp (A : ASection)
    {a b c : Moebius} (f : ActionTransportSquare a b)
    (g : ActionTransportSquare b c) :
    (coordinateTransport A a ⋙
        coordinateTransport A (g.left * f.left)) ⋙
        A.AsectionStateGenerated =
      (coordinateTransport A (g.right * f.right) ⋙
        coordinateTransport A c) ⋙
        A.AsectionStateGenerated :=
  (f.comp g).generated_commutes A

/-- The horizontal orbit--stabilizer square remains commuting when read
through the auxiliary unfolded output formula. -/
theorem orbitStabilizerActionSquare_generated_commutes (A : ASection)
    {X Y : GreatCircle.Base} (f : X ⟶ Y) :
    (coordinateTransport A (projectiveObjectFrame A X) ⋙
        coordinateTransport A
          (orbitStabilizerActionSquare A f).left) ⋙
        A.AsectionStateGenerated =
      (coordinateTransport A
          (orbitStabilizerActionSquare A f).right ⋙
        coordinateTransport A (projectiveObjectFrame A Y)) ⋙
        A.AsectionStateGenerated :=
  (orbitStabilizerActionSquare A f).generated_commutes A

/-- The combined projective/GPV square remains commuting when read through
the auxiliary unfolded output formula. -/
theorem projectiveGpvActionSquare_generated_commutes (A : ASection)
    {X Y : GreatCircle.Base} (f : X ⟶ Y) {k : ℤ}
    (h : GpvTransport A X Y k) :
    (coordinateTransport A (positionedGpvAction A X h 0) ⋙
        coordinateTransport A
          (projectiveGpvActionSquare A f h).left) ⋙
        A.AsectionStateGenerated =
      (coordinateTransport A
          (projectiveGpvActionSquare A f h).right ⋙
        coordinateTransport A
          (projectiveObjectFrame A Y *
            GreatCircle.diskExpAction (h.lift 1))) ⋙
        A.AsectionStateGenerated :=
  (projectiveGpvActionSquare A f h).generated_commutes A

end ASection
