/-
Copyright (c) 2026 Jesse Michael Paul. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jesse Michael Paul
-/
import Concentricity.ProjectiveTotal
import Concentricity.Theorem

/-!
# Quarantined readout of the old slice projection

Everything in this file is retained under `ASection.SliceProjection`.
It elaborates for historical compatibility but is not the readout of the
global `AsectionActionDiagram` and cannot supply the primary
concentricity theorem.
-/

noncomputable section

open CategoryTheory

namespace ASection
namespace SliceProjection

/-- The canonical right-hand side of Riehl 8.3.4 for the completed
A-section action.  This is only the name of `π₀ ∘ A` after the exact
`sectionFunctor A` and its total have been formed. -/
def NaturalComponentDiagram (A : ASection) : GreatCircle.Base ⥤ Type where
  obj _ := CategoryTheory.ConnectedComponents SphereWorld
  map {X Y} f := TypeCat.ofHom (Functor.mapConnectedComponents
    (distinguishedWorldAction ((sectionFunctor A).map f).mob))
  map_id X := by
    ext x
    refine Quotient.inductionOn x fun I => ?_
    rfl
  map_comp f g := by
    ext x
    refine Quotient.inductionOn x fun I => ?_
    rfl

/-- The exact total object's representative on the canonical right-hand side
of 8.3.4.  Kept private: it is an internal of the categorical equivalence,
not another project map. -/
private abbrev naturalTotalColimitClass (A : ASection) (X : TotalA A) :
    Limits.colimit (NaturalComponentDiagram A) :=
  Limits.colimit.ι (NaturalComponentDiagram A) X.base
    (CategoryTheory.ConnectedComponents.mk X.fiber)

private theorem naturalTotalColimitClass_eq_of_hom (A : ASection)
    {X Y : TotalA A} (f : X ⟶ Y) :
    naturalTotalColimitClass A X = naturalTotalColimitClass A Y := by
  have hbase : naturalTotalColimitClass A X =
      Limits.colimit.ι (NaturalComponentDiagram A) Y.base
        (CategoryTheory.ConnectedComponents.mk
          ((distinguishedWorldAction
            ((sectionFunctor A).map f.base).mob).obj X.fiber)) :=
    (Limits.colimit.w_apply (NaturalComponentDiagram A) f.base
      (CategoryTheory.ConnectedComponents.mk X.fiber)).symm
  have hfiber := congrArg
    (fun t => Limits.colimit.ι (NaturalComponentDiagram A) Y.base t)
    (_root_.Quotient.sound (Zigzag.of_hom f.fiber))
  exact hbase.trans hfiber

private theorem naturalTotalColimitClass_eq_of_zigzag (A : ASection)
    {X Y : TotalA A} (h : Zigzag X Y) :
    naturalTotalColimitClass A X = naturalTotalColimitClass A Y := by
  induction h with
  | refl => rfl
  | tail _ hzag ih =>
    refine ih.trans ?_
    rcases hzag with hφ | hφ
    · exact naturalTotalColimitClass_eq_of_hom A hφ.some
    · exact (naturalTotalColimitClass_eq_of_hom A hφ.some).symm

private def naturalFiberInclusion (A : ASection) (b : GreatCircle.Base) :
    SphereWorld ⥤ TotalA A where
  obj I := totalMk A b I
  map φ := ⟨𝟙 b, φ⟩
  map_id I := rfl
  map_comp φ ψ := by
    apply TotalHom.ext A
    case hbase =>
      change 𝟙 b = 𝟙 b ≫ 𝟙 b
      simp
    case hfiber =>
      change eqToHom _ ≫ (φ ≫ ψ) =
        (distinguishedWorldAction
          ((sectionFunctor A).map (𝟙 b)).mob).map φ ≫ ψ
      simp [distinguishedWorldAction, projectiveArrowElement_id]
      apply SphereHom.ext <;> rfl

private def naturalPi0Cocone (A : ASection) :
    Limits.Cocone (NaturalComponentDiagram A) where
  pt := CategoryTheory.ConnectedComponents (TotalA A)
  ι :=
    { app := fun b => TypeCat.ofHom
        (Functor.mapConnectedComponents (naturalFiberInclusion A b))
      naturality := fun X Y f => by
        ext x
        refine _root_.Quotient.inductionOn x fun I => ?_
        simp only [NaturalComponentDiagram, Functor.const_obj_map]
        exact (_root_.Quotient.sound
          (Zigzag.of_hom (totalTransport A f I))).symm }

/-- Riehl 8.3.4 applied to the exact total generated by
`sectionFunctor A`: `π₀(𝒯_A) ≃ colim (π₀ ∘ A)`. -/
noncomputable def projectiveReadout (A : ASection) :
    CategoryTheory.ConnectedComponents (TotalA A) ≃
      Limits.colimit (NaturalComponentDiagram A) where
  toFun := _root_.Quotient.lift (naturalTotalColimitClass A)
    fun _ _ h => naturalTotalColimitClass_eq_of_zigzag A h
  invFun t := Limits.colimit.desc (NaturalComponentDiagram A)
    (naturalPi0Cocone A) t
  left_inv := _root_.Quotient.ind fun X =>
    (Limits.colimit.ι_desc_apply (naturalPi0Cocone A) X.base
      (CategoryTheory.ConnectedComponents.mk X.fiber)).trans rfl
  right_inv t := by
    obtain ⟨b, y, rfl⟩ := Limits.Types.jointly_surjective' t
    refine _root_.Quotient.inductionOn y fun I => ?_
    have hι := Limits.colimit.ι_desc_apply (naturalPi0Cocone A) b
      (CategoryTheory.ConnectedComponents.mk I)
    calc _root_.Quotient.lift (naturalTotalColimitClass A)
          (fun _ _ h => naturalTotalColimitClass_eq_of_zigzag A h)
          (Limits.colimit.desc (NaturalComponentDiagram A) (naturalPi0Cocone A)
            (Limits.colimit.ι (NaturalComponentDiagram A) b
              (CategoryTheory.ConnectedComponents.mk I)))
        = _root_.Quotient.lift (naturalTotalColimitClass A)
            (fun _ _ h => naturalTotalColimitClass_eq_of_zigzag A h)
            ((naturalPi0Cocone A).ι.app b
              (CategoryTheory.ConnectedComponents.mk I)) :=
          congrArg (_root_.Quotient.lift (naturalTotalColimitClass A)
            fun _ _ h => naturalTotalColimitClass_eq_of_zigzag A h) hι
      _ = Limits.colimit.ι (NaturalComponentDiagram A) b
            (CategoryTheory.ConnectedComponents.mk I) := rfl

/-- The C3/C4 consequence population lands in the single class detected by
π₀ and Riehl 8.3.4.  Each C3 output is carried from its own projective
footpoint to the one Weierstrass witness `N` by the already-defined
`GreatCircle.toNHom` leg through the completed A-section transport; the
sphere-world zigzag identifies the simultaneous world readings there. -/
theorem concentricityReadout (A : ASection) :
    ∃ κ : Limits.colimit (NaturalComponentDiagram A),
      ∀ n : ℕ, ∀ I : SphereWorld,
        projectiveReadout A
          (CategoryTheory.ConnectedComponents.mk (zeroTotal A n I)) = κ := by
  let κ := projectiveReadout A
    (CategoryTheory.ConnectedComponents.mk (northTotal A baseWorld))
  refine ⟨κ, ?_⟩
  intro n I
  apply congrArg (projectiveReadout A)
  apply _root_.Quotient.sound
  exact
    (CategoryTheory.Zigzag.of_hom
      (totalTransport A
        (GreatCircle.toNHom (A.sphereZero n).re) I)).trans
      (CategoryTheory.zigzag_obj_of_zigzag
        (naturalFiberInclusion A
          (GreatCircle.pointObj
            (OnePoint.infty : GreatCircle.Point)))
        (sphereWorld_zigzag I baseWorld))

end SliceProjection
end ASection
