/-
Concentricity/TwoWorlds.lean

The slice world 𝒮₂ and the section functor Φ (master `def:two-worlds`,
`thm:section-functor`).

Master `def:two-worlds` (slice-world half, verbatim clauses in docstrings):
"𝒮₂ is the groupoid whose objects are the points of 𝕆* so decomposed, and
whose morphisms are generated by: the *direction* isomorphisms g : w → g·w
for g ∈ G₂ …; and the *band* automorphism families: on each slice sphere
ℂ_I*, the phases u_θ : z ↦ e^{Iθ}z — the Möbius self-maps of S²_I fixing the
value-origin 0, the point at infinity N, and the modulus."

Rendering (statement layer): the free path category on the generator quiver
(direction arrows; band arrows in slice coordinates, φ_v(ζ) → φ_v(e^{iθ}ζ)),
quotiented by the direction-composition relations — the relations
`thm:section-functor` needs for Φ's functoriality. Relations only refine
morphisms and never change connectivity, so every π₀-level statement is
presentation-robust; further band relations (conjugation g∘u_θ = u_θ∘g on
the relabelled slice) are queued with the Phase-4 spine.

`sorry` marks UNFORMALIZED, never UNSOUND (R8).
-/
import Concentricity.Slice
import Mathlib.CategoryTheory.PathCategory.Basic
import Mathlib.CategoryTheory.Quotient

noncomputable section

open CategoryTheory

/-- The objects of the slice world: the points of 𝕆*, carried by a type
synonym so the generator quiver can be installed without leaking a global
`Quiver` instance onto `OnePoint Octonion`. -/
def SliceWorld : Type := OnePoint Octonion

namespace SliceWorld

/-- The generating arrows of 𝒮₂ (master `def:two-worlds`): direction
isomorphisms `w → g·w`; band phases `φ_v(ζ) → φ_v(e^{iθ}ζ)` within each
slice sphere (the fixed points 0 and ∞ receive their phase arrows as loops —
`ζ = 0`, and the `bandInfty` constructor for the shared pole). -/
inductive Gen : SliceWorld → SliceWorld → Type where
  | direction (g : G2) (w : OnePoint Octonion) : Gen w (g • w)
  | band {v : Octonion} (hv : v ∈ Octonion.unitImaginarySphere) (θ : ℝ) (ζ : ℂ) :
      Gen ((Octonion.sliceEmbed v ζ : Octonion) : OnePoint Octonion)
        ((Octonion.sliceEmbed v (Complex.exp (θ * Complex.I) * ζ) : Octonion) : OnePoint Octonion)
  | bandInfty {v : Octonion} (hv : v ∈ Octonion.unitImaginarySphere) (θ : ℝ) :
      Gen OnePoint.infty OnePoint.infty

instance : Quiver SliceWorld := ⟨Gen⟩

instance : MulAction G2 SliceWorld :=
  inferInstanceAs (MulAction G2 (OnePoint Octonion))

/-- The direction-composition relations: exactly what makes the direction
generators compose as G₂ does, so that Φ (master `thm:section-functor`) can
be a functor. Presentation-minimal by design — see the module docstring. -/
inductive Rel : ∀ ⦃w w' : Paths SliceWorld⦄, (w ⟶ w') → (w ⟶ w') → Prop where
  | direction_one (w : SliceWorld) :
      Rel (Quiver.Hom.toPath (Gen.direction 1 w)) (eqToHom (one_smul G2 w).symm)
  | direction_mul (g h : G2) (w : SliceWorld) :
      Rel (Quiver.Hom.toPath (Gen.direction g w) ≫ Quiver.Hom.toPath (Gen.direction h (g • w)))
        (Quiver.Hom.toPath (Gen.direction (h * g) w) ≫ eqToHom (mul_smul h g w))

end SliceWorld

/-- **𝒮₂** (master `def:two-worlds`): the slice world, as the quotient of
the free path category on the generators by the direction-composition
relations. -/
def S2 := CategoryTheory.Quotient SliceWorld.Rel

instance : Category S2 :=
  inferInstanceAs (Category (CategoryTheory.Quotient SliceWorld.Rel))

/-- The canonical object of 𝒮₂ over a point of 𝕆*. -/
def S2.of (w : OnePoint Octonion) : S2 :=
  ⟨w⟩

/-- The canonical object of 𝓗₁ over a point of 𝕆*. -/
def H1.of (x : OnePoint Octonion) : H1 :=
  (x : CategoryTheory.ActionCategory G2 (OnePoint Octonion))

/-- **Φ** (master `thm:section-functor`, verbatim): "For a section A ∈ 𝓡,
the assignment Φ(q) = A(q) on objects, Φ(g : q → g·q) = (g : A(q) → A(g·q))
on morphisms, is a functor of groupoids Φ : 𝓗₁ → 𝒮₂ — *the section
functor*."

Queued (R8): the construction is the Phase-4 assembly of
`def:section-map`(i)/(ii) (values on the own slice sphere; G₂-equivariance
`realize_equivariant`) against the direction relations of `SliceWorld.Rel`.
The object pin is `sectionFunctor_obj` below; the morphism pin
(Φ(g) = the direction generator's class, transported along
`realize_equivariant` by `eqToHom`) is queued with the construction. -/
def sectionFunctor (A : ASection) : H1 ⥤ S2 := by
  sorry

/-- The object pin of `thm:section-functor`: "Φ(q) = A(q) on objects" —
the realization of Concentricity/Slice.lean. Queued (R8). -/
theorem sectionFunctor_obj (A : ASection) (x : OnePoint Octonion) :
    (sectionFunctor A).obj (H1.of x) = S2.of (A.realize x) := by
  sorry
