#!/usr/bin/env python3
"""Codex Stop gate for status-bearing mathematical claims.

Ordinary conversation is untouched. In a provenance formalization phase, a
paragraph that reports a kernel/object/inference/binding status must carry a
current hidden KGT token generated by the ledger. Gap/circularity language is
accepted only with an exact-construction rejection receipt quoting Lean.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import re
import sys


ROOT = pathlib.Path(__file__).resolve().parent.parent
CFG = json.loads((ROOT / ".provenance-project.json").read_text())
CLAIMS = ROOT / ".provenance" / "claims.json"
LEDGER_PDF = ROOT / "output" / "pdf" / "ProvenanceLedger.pdf"
LOCK = pathlib.Path.home() / ".provenance-active"
TOKEN = re.compile(r"KGT\[[^\]]+\]")
CONTROLLED = re.compile(
    r"\b(?:kernel[- ]certified|inference[- ]certified|triple[- ]certified|"
    r"not instantiated|generic (?:proof|theorem|inference)|sorryAx|axiom surface|"
    r"Lean (?:accepted|rejected|proved|certified)|proof (?:is )?open|"
    r"(?:unproved|not proved|not certified|not formalized)|"
    r"bindings? (?:are )?(?:ready|unresolved|open)|(?:not wired|wiring (?:is )?open)|"
    r"declaration (?:is )?open|"
    r"missing mathematics|mathematical gap|proof gap|circular(?:ity)?|"
    r"mathematical mismatch|missing (?:morphism|premise|lemma)|"
    r"(?:proof|theorem|argument) (?:may fail|may be false|is invalid))\b",
    re.IGNORECASE,
)
NEGATIVE = re.compile(
    r"\b(?:missing mathematics|mathematical gap|proof gap|circular(?:ity)?|"
    r"mathematical mismatch|missing (?:morphism|premise|lemma)|"
    r"(?:proof|theorem|argument) (?:may fail|may be false|is invalid))\b",
    re.IGNORECASE,
)

STATUS_RULES: list[tuple[re.Pattern[str], set[str]]] = [
    (re.compile(r"\b(?:kernel[- ]certified|triple[- ]certified|Lean (?:accepted|proved|certified))\b", re.I), {
        "KERNEL_OBJECT_CERTIFIED", "INFERENCE_CERTIFIED",
        "INFERENCE_CERTIFIED_BINDING_OPEN", "INFERENCE_CERTIFIED_WIRING_OPEN",
        "GENERIC_INFERENCE_CERTIFIED",
    }),
    (re.compile(r"\binference[- ]certified\b", re.I), {
        "KERNEL_OBJECT_CERTIFIED", "INFERENCE_CERTIFIED",
        "INFERENCE_CERTIFIED_BINDING_OPEN", "INFERENCE_CERTIFIED_WIRING_OPEN",
        "GENERIC_INFERENCE_CERTIFIED",
    }),
    (re.compile(r"\b(?:not instantiated|generic (?:proof|theorem|inference))\b", re.I), {
        "GENERIC_INFERENCE_CERTIFIED", "GENERIC_AND_PROOF_OPEN",
        "INFERENCE_CERTIFIED_BINDING_OPEN",
    }),
    (re.compile(r"\bsorryAx\b", re.I), {
        "EXACT_OBJECT_PROOF_OPEN", "GENERIC_AND_PROOF_OPEN", "UNAPPROVED_AXIOMS",
    }),
    (re.compile(r"\bdeclaration (?:is )?open\b", re.I), {"DECLARATION_OPEN"}),
    (re.compile(r"\bbindings? (?:are )?ready\b", re.I), {
        "INFERENCE_CERTIFIED_WIRING_OPEN", "KERNEL_OBJECT_CERTIFIED",
    }),
    (re.compile(r"\b(?:bindings? (?:are )?(?:unresolved|open)|not wired)\b", re.I), {
        "INFERENCE_CERTIFIED_BINDING_OPEN", "OPEN_SEAT",
    }),
    (re.compile(r"\bwiring (?:is )?open\b", re.I), {"INFERENCE_CERTIFIED_WIRING_OPEN"}),
    (re.compile(r"\bLean rejected\b", re.I), {
        "CERTIFICATION_CHECK_REJECTED", "EXACT_CONSTRUCTION_REJECTED",
    }),
]


def digest(paths: list[pathlib.Path]) -> str:
    value = hashlib.sha256()
    for path in sorted(paths):
        value.update(str(path.resolve().relative_to(ROOT.resolve())).encode())
        value.update(b"\0")
        value.update(path.read_bytes())
        value.update(b"\0")
    return value.hexdigest()


def current_claims() -> tuple[dict[str, dict[str, object]], str | None]:
    if not CLAIMS.exists():
        return {}, "no generated claim surface; regenerate the provenance ledger"
    try:
        data = json.loads(CLAIMS.read_text())
    except json.JSONDecodeError as error:
        return {}, f"claim surface is malformed: {error}"
    master_hash = digest([ROOT / str(CFG["master"])])
    source_files = list((ROOT / str(CFG["source_dir"])).rglob("*.lean"))
    source_hash = digest(source_files) if source_files else "no Lean sources found"
    if data.get("master_hash") != master_hash or data.get("source_hash") != source_hash:
        return {}, "claim surface is stale; regenerate the provenance ledger"
    if not LEDGER_PDF.exists() or data.get("ledger_pdf_hash") != hashlib.sha256(
        LEDGER_PDF.read_bytes()
    ).hexdigest():
        return {}, "rendered provenance ledger is missing or stale; regenerate it"
    claims = data.get("claims", [])
    if not isinstance(claims, list):
        return {}, "claim surface has no claims list"
    return {
        str(row.get("token")): row for row in claims
        if isinstance(row, dict) and isinstance(row.get("token"), str)
    }, None


def check_message(message: str) -> list[str]:
    claims, error = current_claims()
    controlled = [part.strip() for part in re.split(r"\n\s*\n", message)
                  if CONTROLLED.search(part)]
    if not controlled:
        return []
    if error:
        return [error]
    problems: list[str] = []
    for paragraph in controlled:
        tokens = TOKEN.findall(paragraph)
        valid = [claims[token] for token in tokens if token in claims]
        if not valid:
            problems.append("status-bearing paragraph has no current KGT receipt token")
            continue
        statuses = {str(row.get("status")) for row in valid}
        for pattern, accepted in STATUS_RULES:
            if pattern.search(paragraph) and statuses.isdisjoint(accepted):
                problems.append(
                    "status-bearing paragraph uses a current token for a different machine state"
                )
        if NEGATIVE.search(paragraph) and not any(
            row.get("status") == "EXACT_CONSTRUCTION_REJECTED" for row in valid
        ):
            problems.append(
                "gap/circularity language lacks an EXACT_CONSTRUCTION_REJECTED receipt "
                "for the author's exact term and Lean's literal unsatisfied type"
            )
    return problems


def stop_hook() -> int:
    try:
        payload = json.load(sys.stdin)
    except json.JSONDecodeError:
        print(json.dumps({"decision": "block", "reason": "claim gate received malformed hook input"}))
        return 0
    active = LOCK.read_text().strip() if LOCK.exists() else ""
    if pathlib.Path(active).resolve() != ROOT.resolve() or CFG.get("phase", "formalization") == "authoring":
        print("{}")
        return 0
    problems = check_message(str(payload.get("last_assistant_message") or ""))
    if problems:
        reason = (
            "PROVENANCE CLAIM GATE - revise the final status report. "
            + " ".join(dict.fromkeys(problems))
            + " Run `python3 tools/claim_gate.py --list` and place the matching token "
              "in the same paragraph as an HTML comment, for example `<!-- KGT[...] -->`."
        )
        print(json.dumps({"decision": "block", "reason": reason}))
    else:
        print("{}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--list", action="store_true")
    parser.add_argument("--check-message")
    args = parser.parse_args()
    if args.list:
        claims, error = current_claims()
        if error:
            print(error, file=sys.stderr)
            return 1
        for token, row in sorted(claims.items()):
            print(token, row.get("status"))
        return 0
    if args.check_message:
        problems = check_message(pathlib.Path(args.check_message).read_text())
        for problem in problems:
            print(problem)
        return 1 if problems else 0
    return stop_hook()


if __name__ == "__main__":
    raise SystemExit(main())
