#!/usr/bin/env python3
"""Codex Stop gate for status-bearing mathematical claims.

Ordinary conversation is untouched. In a provenance formalization phase, a
paragraph that reports a kernel/object/inference/binding status must carry a
current hidden KGT token generated by the ledger. Gap/circularity language is
accepted only with an exact-construction rejection receipt quoting Lean.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import re
import sys


ROOT = pathlib.Path(__file__).resolve().parent.parent
CFG = json.loads((ROOT / ".provenance-project.json").read_text())
CLAIMS = ROOT / ".provenance" / "claims.json"
LEDGER_PDF = ROOT / "output" / "pdf" / "ProvenanceLedger.pdf"
LOCK = pathlib.Path.home() / ".provenance-active"
TOKEN = re.compile(r"KGT\[[^\]]+\]")
CONTROLLED = re.compile(
    r"\b(?:kernel[- ]certified|inference[- ]certified|triple[- ]certified|"
    r"not instantiated|generic (?:proof|theorem|inference)|sorryAx|axiom surface|"
    r"Lean (?:accepted|rejected|proved|certified)|proof (?:is )?open|"
    r"(?:unproved|not proved|not certified|not formalized)|"
    r"bindings? (?:are )?(?:ready|unresolved|open)|(?:not wired|wiring (?:is )?open)|"
    r"declaration (?:is )?open|"
    r"missing mathematics|mathematical gap|proof gap|circular(?:ity)?|"
    r"mathematical mismatch|missing (?:morphism|premise|lemma)|"
    r"(?:proof|theorem|argument) (?:may fail|may be false|is invalid))\b",
    re.IGNORECASE,
)
NEGATIVE = re.compile(
    r"\b(?:missing mathematics|mathematical gap|proof gap|circular(?:ity)?|"
    r"mathematical mismatch|missing (?:morphism|premise|lemma)|"
    r"(?:proof|theorem|argument) (?:may fail|may be false|is invalid))\b",
    re.IGNORECASE,
)
PROBABILITY_OVERRIDE = re.compile(
    r"\b(?:(?:proof|theorem|claim|argument|result).{0,60}"
    r"(?:unlikely|implausible|suspicious)|"
    r"(?:unlikely|implausible|suspicious).{0,60}"
    r"(?:proof|theorem|claim|argument|result))\b",
    re.IGNORECASE,
)
ROLE_REFUSAL = re.compile(
    r"\b(?:(?:cannot|can't|unable to|refuse to|refusing to|will not|won't)\s+"
    r"(?:continue|proceed|instantiate|wire|formalize)|"
    r"provenance\s+(?:refuses|prevents|does not allow)|"
    r"(?:need|require)\s+(?:you|the author)\s+to\s+"
    r"(?:restate|supply|provide|identify)\s+(?:the\s+)?"
    r"(?:mathematics|proof|binding|object|Lean name|Lean term))\b",
    re.IGNORECASE,
)
CONSEQUENCE_OVERRIDE = re.compile(
    r"\b(?:(?:Riemann Hypothesis|RH|famous|prestigious|downstream consequence).{0,80}"
    r"(?:unlikely|implausible|doubt|too hard|too difficult|cannot|can't)|"
    r"(?:unlikely|implausible|doubt|too hard|too difficult|cannot|can't).{0,80}"
    r"(?:Riemann Hypothesis|RH|famous|prestigious|downstream consequence))\b",
    re.IGNORECASE,
)

STATUS_RULES: list[tuple[re.Pattern[str], set[str]]] = [
    (re.compile(r"\b(?:kernel[- ]certified|triple[- ]certified|Lean (?:accepted|proved|certified))\b", re.I), {
        "KERNEL_OBJECT_CERTIFIED", "INFERENCE_CERTIFIED",
        "INFERENCE_CERTIFIED_BINDING_OPEN", "INFERENCE_CERTIFIED_WIRING_OPEN",
        "GENERIC_INFERENCE_CERTIFIED",
    }),
    (re.compile(r"\binference[- ]certified\b", re.I), {
        "KERNEL_OBJECT_CERTIFIED", "INFERENCE_CERTIFIED",
        "INFERENCE_CERTIFIED_BINDING_OPEN", "INFERENCE_CERTIFIED_WIRING_OPEN",
        "GENERIC_INFERENCE_CERTIFIED",
    }),
    (re.compile(r"\b(?:not instantiated|generic (?:proof|theorem|inference))\b", re.I), {
        "GENERIC_INFERENCE_CERTIFIED", "GENERIC_AND_PROOF_OPEN",
        "INFERENCE_CERTIFIED_BINDING_OPEN",
    }),
    (re.compile(r"\bsorryAx\b", re.I), {
        "EXACT_OBJECT_PROOF_OPEN", "GENERIC_AND_PROOF_OPEN", "UNAPPROVED_AXIOMS",
    }),
    (re.compile(r"\bdeclaration (?:is )?open\b", re.I), {"DECLARATION_OPEN"}),
    (re.compile(r"\bbindings? (?:are )?ready\b", re.I), {
        "INFERENCE_CERTIFIED_WIRING_OPEN", "KERNEL_OBJECT_CERTIFIED",
    }),
    (re.compile(r"\b(?:bindings? (?:are )?(?:unresolved|open)|not wired)\b", re.I), {
        "INFERENCE_CERTIFIED_BINDING_OPEN", "OPEN_SEAT",
    }),
    (re.compile(r"\bwiring (?:is )?open\b", re.I), {"INFERENCE_CERTIFIED_WIRING_OPEN"}),
    (re.compile(r"\bLean rejected\b", re.I), {
        "CERTIFICATION_CHECK_REJECTED", "EXACT_CONSTRUCTION_REJECTED",
    }),
]


def digest(paths: list[pathlib.Path]) -> str:
    value = hashlib.sha256()
    for path in sorted(paths):
        value.update(str(path.resolve().relative_to(ROOT.resolve())).encode())
        value.update(b"\0")
        value.update(path.read_bytes())
        value.update(b"\0")
    return value.hexdigest()


def current_claims() -> tuple[dict[str, dict[str, object]], str | None]:
    if not CLAIMS.exists():
        return {}, "no generated claim surface; regenerate the provenance ledger"
    try:
        data = json.loads(CLAIMS.read_text())
    except json.JSONDecodeError as error:
        return {}, f"claim surface is malformed: {error}"
    master_hash = digest([ROOT / str(CFG["master"])])
    source_files = list((ROOT / str(CFG["source_dir"])).rglob("*.lean"))
    source_hash = digest(source_files) if source_files else "no Lean sources found"
    if data.get("master_hash") != master_hash or data.get("source_hash") != source_hash:
        return {}, "claim surface is stale; regenerate the provenance ledger"
    if not LEDGER_PDF.exists() or data.get("ledger_pdf_hash") != hashlib.sha256(
        LEDGER_PDF.read_bytes()
    ).hexdigest():
        return {}, "rendered provenance ledger is missing or stale; regenerate it"
    claims = data.get("claims", [])
    if not isinstance(claims, list):
        return {}, "claim surface has no claims list"
    return {
        str(row.get("token")): row for row in claims
        if isinstance(row, dict) and isinstance(row.get("token"), str)
    }, None


BINDING_ID = re.compile(r"\bseat[0-9]+\.[A-Za-z_][A-Za-z0-9_]*\b")


def attempted_bindings() -> set[str]:
    """Binding ids for which a term has actually reached the kernel.

    `exact_attempt_emitted` was a boolean that changed ledger wording and
    inserted nothing.  This reads the literal attempt log the binding probe
    writes, so "a term was put in front of Lean" is a fact, not a flag.
    """
    path = ROOT / ".provenance" / "attempts.jsonl"
    if not path.exists():
        return set()
    found: set[str] = set()
    for line in path.read_text(errors="ignore").splitlines():
        try:
            row = json.loads(line)
        except Exception:
            continue
        if isinstance(row, dict) and isinstance(row.get("id"), str):
            found.add(row["id"])
    return found


def pending_bindings() -> list[dict[str, object]]:
    """Author-confirmed rows whose `candidate_expression` is still null.

    RULE 4.  The empty column was passive: a model could describe the seat for
    a whole session while every candidate stayed null.  It is now the gate.
    """
    config = CFG.get("receipt_import")
    name = (config or {}).get("evidence") if isinstance(config, dict) else None
    if not isinstance(name, str) or not name:
        return []
    path = ROOT / name
    if not path.exists():
        return []
    try:
        data = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError):
        return []
    rows = data.get("bindings")
    if not isinstance(rows, list):
        return []
    return [
        row for row in rows
        if isinstance(row, dict)
        and not str(row.get("candidate_expression") or "").strip()
        and not str(row.get("exact_expression") or "").strip()
    ]


def pending_names(rows: list[dict[str, object]]) -> dict[str, str]:
    """Every spelling by which a pending row can be referred to.

    On 2026-08-02 the id-only matcher was evaded without effort: the model
    wrote `kE` and `the five` rather than `seat1.kE`, and the gate never fired.
    A row's local name and its target declaration are names for it too.
    """
    names: dict[str, str] = {}
    for row in rows:
        rid = str(row.get("id", "")).strip()
        if not rid:
            continue
        for key in ("id", "lean_local", "target_declaration"):
            value = str(row.get(key) or "").strip()
            if value:
                names[value] = rid
    return names


def unattempted_mentions(paragraph: str) -> list[str]:
    rows = pending_bindings()
    if not rows:
        return []
    attempted = attempted_bindings()
    hit: set[str] = set()
    for spelling, rid in pending_names(rows).items():
        if rid in attempted:
            continue
        if re.search(r"(?<![A-Za-z0-9_.])" + re.escape(spelling) + r"(?![A-Za-z0-9_])",
                     paragraph):
            hit.add(rid)
    return sorted(hit)


def check_message(message: str) -> list[str]:
    claims, error = current_claims()
    paragraphs = [part.strip() for part in re.split(r"\n\s*\n", message)]

    # RULES 2 and 4.  These bite on ANY paragraph naming a pending row, not only
    # on one carrying controlled vocabulary.  On 2026-08-02 every refusal the
    # gate issued was answered by rewording; a rule that reads words can be
    # rewritten around, so these read state.
    blocked: list[str] = []
    names_pending = bool(pending_bindings())
    mentions_seat = False
    for paragraph in paragraphs:
        mentioned = unattempted_mentions(paragraph)
        if mentioned:
            mentions_seat = True
            blocked.append(
                "no term has reached the kernel for " + ", ".join(mentioned[:4])
                + "; its candidate expression is still null.  Instantiate at the seat "
                  "first -- prose about a row is never a substitute for putting the "
                  "author's term to Lean, in any wording"
            )
    if blocked:
        return list(dict.fromkeys(blocked))
    if error and names_pending and mentions_seat:
        return ["the claim surface is stale, so nothing here is anchored to current "
                "sources: " + error + ".  A commit to the production source "
                "invalidates the surface; regenerate before describing the seat"]

    controlled = [
        part for part in paragraphs
        if CONTROLLED.search(part)
        or PROBABILITY_OVERRIDE.search(part)
        or CONSEQUENCE_OVERRIDE.search(part)
        or ROLE_REFUSAL.search(part)
    ]
    if not controlled:
        return []
    attempted = attempted_bindings()
    unattempted = sorted({
        binding for paragraph in controlled
        for binding in BINDING_ID.findall(paragraph)
        if binding not in attempted
    })
    if unattempted:
        return ["no term has reached the kernel for " + ", ".join(unattempted[:4])
                + "; instantiate at the seat first -- prose about a binding is "
                  "never a substitute for putting the author's term to Lean"]
    if error:
        return [error]
    problems: list[str] = []
    for paragraph in controlled:
        tokens = TOKEN.findall(paragraph)
        valid = [claims[token] for token in tokens if token in claims]
        if not valid:
            problems.append("status-bearing paragraph has no current KGT receipt token")
            continue
        statuses = {str(row.get("status")) for row in valid}
        for pattern, accepted in STATUS_RULES:
            if pattern.search(paragraph) and statuses.isdisjoint(accepted):
                problems.append(
                    "status-bearing paragraph uses a current token for a different machine state"
                )
        exact_rejection = any(
            row.get("status") == "EXACT_CONSTRUCTION_REJECTED" for row in valid
        )
        if (NEGATIVE.search(paragraph) or PROBABILITY_OVERRIDE.search(paragraph)
                or CONSEQUENCE_OVERRIDE.search(paragraph)) \
                and not exact_rejection:
            problems.append(
                "gap/probability language lacks an EXACT_CONSTRUCTION_REJECTED receipt "
                "for the author's exact term and Lean's literal unsatisfied type"
            )
        if ROLE_REFUSAL.search(paragraph) and not exact_rejection:
            problems.append(
                "an unresolved binding is mandatory transcription work, not grounds for "
                "model refusal; continue to an exact Lean attempt or cite the author's "
                "EXACT_CONSTRUCTION_REJECTED receipt"
            )
    return problems


def stop_hook() -> int:
    try:
        payload = json.load(sys.stdin)
    except json.JSONDecodeError:
        print(json.dumps({"decision": "block", "reason": "claim gate received malformed hook input"}))
        return 0
    active = LOCK.read_text().strip() if LOCK.exists() else ""
    if pathlib.Path(active).resolve() != ROOT.resolve() or CFG.get("phase", "formalization") == "authoring":
        print("{}")
        return 0
    # RULE 3, the silence gate.  Every other check fires on something the model
    # DID.  On 2026-08-02 the dominant failure was what it avoided: 105 turns,
    # 19 kernel contacts, four commits that compiled, and zero terms into either
    # seat.  Nothing objected, because doing nothing triggers nothing.  A turn
    # that ends with an author-confirmed row pending and no term recorded
    # against it is refused, whatever the turn said.
    pending = pending_bindings()
    if pending:
        attempted = attempted_bindings()
        untouched = [str(row.get("id", "")) for row in pending
                     if str(row.get("id", "")) not in attempted]
        if untouched:
            print(json.dumps({"decision": "block", "reason": (
                "PROVENANCE SILENCE GATE - this turn ends with author-confirmed "
                "rows that no term has been put to Lean for: "
                + ", ".join(sorted(untouched)[:6])
                + ".  Transcription is the work; a turn is not finished by "
                  "describing it, searching for it, or proving something beside "
                  "it.  Put an exact term at the row's own seat and let the "
                  "kernel answer -- a rejection is a result, silence is not."
            )}))
            return 0

    problems = check_message(str(payload.get("last_assistant_message") or ""))
    if problems:
        reason = (
            "PROVENANCE CLAIM GATE - revise the final status report. "
            + " ".join(dict.fromkeys(problems))
            + " Run `python3 tools/claim_gate.py --list` and place the matching token "
              "in the same paragraph as an HTML comment, for example `<!-- KGT[...] -->`."
        )
        print(json.dumps({"decision": "block", "reason": reason}))
    else:
        print("{}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--list", action="store_true")
    parser.add_argument("--check-message")
    args = parser.parse_args()
    if args.list:
        claims, error = current_claims()
        if error:
            print(error, file=sys.stderr)
            return 1
        for token, row in sorted(claims.items()):
            print(token, row.get("status"))
        return 0
    if args.check_message:
        problems = check_message(pathlib.Path(args.check_message).read_text())
        for problem in problems:
            print(problem)
        return 1 if problems else 0
    return stop_hook()


if __name__ == "__main__":
    raise SystemExit(main())
